title: Learning Github Pages
author: CrazyChickenDev
email: dannychukz15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I actually don't have any description in mind now. Just learning as much
  as i can with limited data..lol

# social links
twitter_username: CrazyChickenDev # DO NOT include the @ character, or else the build will fail!
github_username:  CrazyChickenDev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
